import * as fs from 'fs'
import * as path from 'path'

interface FeatureFlags {
  onlineClasses: boolean
  examResults: boolean
  parentPortal: boolean
  assignmentSubmission: boolean
  libraryManagement: boolean
  transportManagement: boolean
  feeManagement: boolean
  attendanceTracking: boolean
  smsNotifications: boolean
  whatsappAutomation: boolean
  aiChatbot: boolean
  advancedAnalytics: boolean
}

const DEFAULT_FLAGS: FeatureFlags = {
  onlineClasses: false,
  examResults: false,
  parentPortal: false,
  assignmentSubmission: false,
  libraryManagement: false,
  transportManagement: false,
  feeManagement: false,
  attendanceTracking: false,
  smsNotifications: false,
  whatsappAutomation: false,
  aiChatbot: false,
  advancedAnalytics: false,
}

function loadFeatures(): FeatureFlags {
  // Try loading from features.json first (generated by inject.ts)
  const jsonPath = path.resolve(__dirname, 'features.json')
  if (fs.existsSync(jsonPath)) {
    try {
      const raw = fs.readFileSync(jsonPath, 'utf-8')
      return { ...DEFAULT_FLAGS, ...JSON.parse(raw) }
    } catch {
      // fall through to env vars
    }
  }

  // Fallback to environment variables
  return {
    onlineClasses: process.env.FEATURE_ONLINE_CLASSES === 'true',
    examResults: process.env.FEATURE_EXAM_RESULTS === 'true',
    parentPortal: process.env.FEATURE_PARENT_PORTAL === 'true',
    assignmentSubmission: process.env.FEATURE_ASSIGNMENT_SUBMISSION === 'true',
    libraryManagement: process.env.FEATURE_LIBRARY_MANAGEMENT === 'true',
    transportManagement: process.env.FEATURE_TRANSPORT_MANAGEMENT === 'true',
    feeManagement: process.env.FEATURE_FEE_MANAGEMENT === 'true',
    attendanceTracking: process.env.FEATURE_ATTENDANCE_TRACKING === 'true',
    smsNotifications: process.env.FEATURE_SMS_NOTIFICATIONS === 'true',
    whatsappAutomation: process.env.FEATURE_WHATSAPP_AUTOMATION === 'true',
    aiChatbot: process.env.FEATURE_AI_CHATBOT === 'true',
    advancedAnalytics: process.env.FEATURE_ADVANCED_ANALYTICS === 'true',
  }
}

export const features = loadFeatures()

export function isFeatureEnabled(feature: keyof FeatureFlags): boolean {
  return features[feature] === true
}
